<?php

/**
 * Implements hook_help().
 */
function commerce_reports_patterns_help($path, $arg) {
  switch ($path) {
    case 'admin/commerce/reports/patterns':
      return '<p>' . t('Association rules are if/then statements that help uncover relationships between seemingly unrelated data in a relational database or other information repository. An example of an association rule would be "If a customer buys a dozen eggs, he is 80% likely to also purchase milk."') . '</p>';
      
  }
}

/**
 * Implements hook_menu().
 */
function commerce_reports_patterns_menu() {
  $items = array();
  
  $items['admin/commerce/reports/patterns'] = array(
    'title' => 'Patterns',
    'description' => 'Discover frequent patterns for your store.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_reports_patterns_form'),
    'access arguments' => array('access commerce reports patterns'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 100,
  );
  
  return $items;
}

function commerce_reports_patterns_form($form, &$form_state) {
  $form['min_support'] = array(
    '#type' => 'textfield',
    '#title' => t('Minimum support'),
    '#description' => t('The minimum support should be a decimal between 0 and 1 that indicates what the minimum relative amount of transactions an item set requires to be frequent.'),
    '#size' => 6,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Generate'),
  );
  
  return $form;
}

function commerce_reports_patterns_form_validate($form, &$form_state) {
  $min_support = (float) $form_state['values']['min_support'];
  
  if (($min_support <= 0) || ($min_support >= 1)) {
    form_set_error('min_support', t('The minimum support should be a value between 0 and 1.'));
  }
}

function commerce_reports_patterns_form_submit($form, &$form_state) {
  $min_support = (float) $form_state['values']['min_support'];
  
  $batch = array(
    'title' => t('Generating frequent itemsets'),
    'operations' => array(
      array('commerce_reports_patterns_load', array($min_support)),
      array('commerce_reports_patterns_mine', array()),
    ),
    'finished' => 'commerce_reports_patterns_finished',
    'file' => drupal_get_path('module', 'commerce_reports_patterns') . '/commerce_reports_patterns.batch.inc',
  );
  
  batch_set($batch);
}
