<?php

/**
 * Implements hook_help().
 */
function commerce_reports_patterns_help($path, $arg) {
  switch ($path) {
    case 'admin/commerce/reports/patterns':
      return '<p>' . t('Association rules are if/then statements that help uncover relationships between seemingly unrelated data in a relational database or other information repository. An example of an association rule would be "If a customer buys a dozen eggs, he is 80% likely to also purchase milk."') . '</p>';
      
  }
}

/**
 * Implements hook_menu().
 */
function commerce_reports_patterns_menu() {
  $items = array();
  
  $items['admin/commerce/reports/patterns'] = array(
    'title' => 'Patterns',
    'description' => 'Discover frequent patterns for your store.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_reports_patterns_form'),
    'access arguments' => array('access commerce reports patterns'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'commerce_reports_patterns.admin.inc',
    'weight' => 100,
  );
  $items['admin/commerce/reports/patterns/view'] = array(
    'title' => 'Report',
    //'description' => '',
    'page callback' => 'commerce_reports_patterns_view',
    'access arguments' => array('access commerce reports patterns'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'commerce_reports_patterns.admin.inc',
  );
  
  return $items;
}

/**
 * Implementation of hook_permission().
 */
function commerce_reports_patterns_permission() {
  return array(
    'access commerce reports patterns' => array(
      'title' => t('Access commerce reports patterns'),
    ),
  );
}
